version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["/app/entrypoint.sh", "dev"]
    volumes:
      - .:/app:cached
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "*"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
