# Generated by Django 5.1.2 on 2025-08-05 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('procedures', '0003_alter_clinicalexam_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DentalProcedure',
        ),
        migrations.AlterField(
            model_name='clinicalexam',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment'),
        ),
    ]
